.PHONY: clean All

All:
	@echo "----------Building project:[ Leetcode_Studies - Debug ]----------"
	@cd "Leetcode_Studies" && "$(MAKE)" -f  "Leetcode_Studies.mk"
clean:
	@echo "----------Cleaning project:[ Leetcode_Studies - Debug ]----------"
	@cd "Leetcode_Studies" && "$(MAKE)" -f  "Leetcode_Studies.mk" clean
